apiVersion: apps/v1
kind: Deployment
metadata:
  name: num-rec-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: num-rec-backend
  template:
    metadata:
      labels:
        app: num-rec-backend
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: num-rec-data
      containers:
        - name: num-rec-backend
          image: ghcr.io/nmiklavcic/num-rec-backend:latest
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: data
              mountPath: /app/data